-- Seed the current static catalogue into public.products.
-- Safe to re-run: existing rows (including admin edits) are left untouched.
insert into public.products (id, name, price, compare_at, rating, reviews, badge, image, category, sku, colour, craft, fabric, fit, occasion, description, details, active, sort_order)
values
('p1','Ivory Hand-Embroidered Kurti',1499,1899,4.8,32,'New','images/product-1.jpg?v=4','pastel classic','LC-IV-101','Ivory','Floral thread embroidery','Lightweight fabric; exact composition is confirmed per piece','Straight, easy silhouette','Everyday elegance and intimate celebrations','A quiet ivory kurti selected for its delicate floral surface work and versatile, light-toned finish.','["Soft neutral palette","Embroidered neckline and front panel","Designed for easy day-to-evening styling"]',true,1),
('p2','Sunshine Yellow Chikankari',1699,1999,4.7,27,'','images/product-2.jpg?v=4','pastel bright','LC-YW-102','Sunshine yellow','Tone-led floral embroidery','Lightweight fabric; exact composition is confirmed per piece','Relaxed straight silhouette','Brunches, daytime gatherings and festive mornings','A cheerful yellow style that keeps the embroidery graceful while bringing colour to everyday dressing.','["Bright daytime colour","Detailed embroidered neckline","Pairs easily with white or neutral bottoms"]',true,2),
('p3','Pastel Blue & Peach Collection',1799,null,4.6,19,'','images/product-3.jpg?v=4','pastel','LC-BP-103','Pastel blue and peach options','Delicate neckline embroidery','Lightweight fabric; exact composition is confirmed per piece','Comfort-led straight silhouette','Workdays, lunches and relaxed celebrations','An airy pastel edit with carefully detailed necklines and a soft, understated colour story.','["Multiple pastel colour options","Fine floral thread detailing","Easy to layer with a dupatta"]',true,3),
('p4','Ruby Red Embroidered Kurti',1999,2499,4.9,41,'Bestseller','images/product-4.jpg?v=4','bright','LC-RD-104','Ruby red','Statement floral embroidery','Lightweight fabric; exact composition is confirmed per piece','Straight festive silhouette','Festive evenings and family occasions','A rich red kurti with expressive floral handwork for days when the embroidery should take centre stage.','["Saturated festive colour","High-contrast floral detailing","Statement piece for simple accessories"]',true,4),
('p5','Classic Black Chikankari',2199,2599,4.7,23,'','images/product-4.jpg?v=4','classic','LC-BK-105','Classic black','Contrast-inspired thread detailing','Lightweight fabric; exact composition is confirmed per piece','Timeless straight silhouette','Evening wear and smart everyday dressing','A timeless dark-toned style that makes the embroidery feel crisp, graphic and easy to accessorise.','["Classic monochrome mood","Clean straight profile","Suitable for understated evening styling"]',true,5),
('p6','Blush Pink Chikankari',2299,null,4.5,17,'','images/product-5.jpg?v=4','pastel','LC-PK-106','Blush pink','Graceful botanical embroidery','Lightweight fabric; exact composition is confirmed per piece','Relaxed feminine silhouette','Day celebrations and elegant casual wear','A gentle pink kurti with botanical-inspired threadwork and an easy, feminine character.','["Soft blush palette","Botanical embroidery accents","Works with pearl or silver-toned accessories"]',true,6),
('p7','Fresh Green Embroidered Kurti',2499,2999,4.8,29,'','images/product-5.jpg?v=4','bright','LC-GR-107','Fresh green','Botanical-inspired threadwork','Lightweight fabric; exact composition is confirmed per piece','Easy straight silhouette','Festive days, lunches and colour-led styling','A fresh green statement with botanical detailing and a lively colour designed to brighten simple separates.','["Fresh seasonal colour","Floral and leaf-inspired work","Designed to stand out with neutral bottoms"]',true,7),
('p8','Festive Multicolour Kurti',2699,null,4.6,21,'','images/product-6.jpg?v=4','bright','LC-MC-108','Multicolour floral palette','Colourful floral embroidery','Lightweight fabric; exact composition is confirmed per piece','Comfort-led festive silhouette','Festivals, gifting and joyful gatherings','A colourful embroidered piece for festive wardrobes, combining playful florals with an easy silhouette.','["Multicolour embroidery","Festive focal piece","Minimal jewellery is enough to complete the look"]',true,8),
('p9','Crimson Floral Handwork',2799,3299,4.9,36,'','images/product-7.jpg?v=4','classic bright','LC-CR-109','Crimson red','Dense floral threadwork','Lightweight fabric; exact composition is confirmed per piece','Classic straight silhouette','Traditional occasions and evening celebrations','A deep crimson style with traditional floral character and a richer embroidered finish.','["Deep celebration-ready tone","Traditional floral arrangement","Strong standalone festive look"]',true,9),
('p10','Emerald Green Handwork',2999,null,4.7,26,'Premium','images/product-8.jpg?v=4','classic bright','LC-EM-110','Emerald green','Intricate statement embroidery','Lightweight fabric; exact composition is confirmed per piece','Elegant straight silhouette','Festive evenings and special gifting','A jewel-toned green kurti selected for intricate embroidery and a polished special-occasion mood.','["Jewel-toned colour","Intricate floral surface detail","Premium statement in the current edit"]',true,10)
on conflict (id) do nothing;
