-- Lakhnavi Chikankari account, profile and paid-order schema.
-- Run this entire file once in the Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  address text,
  city text,
  state text,
  pincode text,
  updated_at timestamptz default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text,
  phone text,
  address text,
  city text,
  state text,
  pincode text,
  items jsonb default '[]'::jsonb,
  total_amount integer,
  amount integer,
  currency text default 'INR',
  payment_status text default 'paid',
  order_status text default 'pending',
  status text,
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  tracking_reference text,
  admin_note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Keep the administrator list private. The browser never receives this table;
-- it can only ask the security-definer function below whether the current
-- signed-in email is approved.
create table if not exists public.order_admins (
  email text primary key,
  created_at timestamptz default now()
);

-- Upgrade older versions of the orders table without deleting existing data.
alter table public.orders add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.orders add column if not exists phone text;
alter table public.orders add column if not exists address text;
alter table public.orders add column if not exists city text;
alter table public.orders add column if not exists state text;
alter table public.orders add column if not exists pincode text;
alter table public.orders add column if not exists items jsonb default '[]'::jsonb;
alter table public.orders add column if not exists total_amount integer;
alter table public.orders add column if not exists payment_status text default 'paid';
alter table public.orders add column if not exists order_status text default 'pending';
alter table public.orders add column if not exists razorpay_signature text;
alter table public.orders add column if not exists tracking_reference text;
alter table public.orders add column if not exists admin_note text;
alter table public.orders add column if not exists updated_at timestamptz default now();

-- New payments do not store the Razorpay signature. Keep the legacy column so
-- existing deployments can be upgraded without deleting historical rows.
comment on column public.orders.razorpay_signature is 'Legacy only; new application versions do not store payment signatures.';

create unique index if not exists orders_razorpay_order_id_key on public.orders (razorpay_order_id);
create unique index if not exists orders_razorpay_payment_id_key on public.orders (razorpay_payment_id);
create index if not exists orders_user_created_idx on public.orders (user_id, created_at desc);
create index if not exists orders_status_created_idx on public.orders (order_status, created_at desc);

alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_admins enable row level security;

create or replace function public.is_order_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.order_admins
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_order_admin() from public, anon;
grant execute on function public.is_order_admin() to authenticated;

drop policy if exists "Customers can read their profile" on public.profiles;
drop policy if exists "Customers can create their profile" on public.profiles;
drop policy if exists "Customers can update their profile" on public.profiles;
drop policy if exists "Customers can read their orders" on public.orders;
drop policy if exists "Order admins can read orders" on public.orders;
drop policy if exists "Order admins can update fulfilment" on public.orders;

create policy "Customers can read their profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

create policy "Customers can create their profile"
  on public.profiles for insert
  to authenticated
  with check (auth.uid() = id);

create policy "Customers can update their profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Customers can read their orders"
  on public.orders for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Order admins can read orders"
  on public.orders for select
  to authenticated
  using (public.is_order_admin());

create policy "Order admins can update fulfilment"
  on public.orders for update
  to authenticated
  using (public.is_order_admin())
  with check (public.is_order_admin());

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.orders from anon, authenticated;
revoke all on table public.order_admins from anon, authenticated;
grant select, insert, update on table public.profiles to authenticated;
grant select on table public.orders to authenticated;
grant update (order_status, tracking_reference, admin_note, updated_at) on table public.orders to authenticated;
